version: "3.8"
services:
  headnode:
    image: nsimakov/slurm_sim_head_node:6
    hostname: headnode
    shm_size: 64M
    command: ["sshd", "munged", "mysqld", "/opt/cluster/vctools/add_system_users.sh", "-loop"]
    # "/opt/cluster/vctools/start_head_node.sh" is intentionally removed here
    # run_vc.sh will start slurm services in right order and will track time
    networks:
      network1:
        ipv4_address: 172.32.0.11
    volumes:
      - './results:/root/results'
      - './etc:/etc/slurm'
      - './vctools:/opt/cluster/vctools'
      - './job_traces:/opt/cluster/job_traces'
      - './log:/var/log/slurm'
      - './home:/home'
      - './../../slurm_sim_tools:/opt/cluster/slurm_sim_tools'
    cpuset: '0-3'
networks:
  network1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.32.0.0/21"
